In [1]:
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [2]:
DATA_PATH = Path("../data/raw")

In [3]:
customers = pd.read_csv(DATA_PATH / "olist_customers_dataset.csv")
geolocation = pd.read_csv(DATA_PATH / "olist_geolocation_dataset.csv")
order_items = pd.read_csv(DATA_PATH / "olist_order_items_dataset.csv")
order_payments = pd.read_csv(DATA_PATH / "olist_order_payments_dataset.csv")
order_reviews = pd.read_csv(DATA_PATH / "olist_order_reviews_dataset.csv")
orders = pd.read_csv(DATA_PATH / "olist_orders_dataset.csv")
products = pd.read_csv(DATA_PATH / "olist_products_dataset.csv")
sellers = pd.read_csv(DATA_PATH / "olist_sellers_dataset.csv")
category_translation = pd.read_csv(DATA_PATH / "product_category_name_translation.csv")

In [4]:
datasets = {
    "Customers": customers,
    "Geolocation": geolocation,
    "Order Items": order_items,
    "Order Payments": order_payments,
    "Order Reviews": order_reviews,
    "Orders": orders,
    "Products": products,
    "Sellers": sellers,
    "Category Translation": category_translation
}

In [5]:
print("=" * 70)
print("DATASET SHAPES")
print("=" * 70)

for name, df in datasets.items():
    print(f"{name:<25} {df.shape}")

======================================================================
DATASET SHAPES
======================================================================
Customers                 (99441, 5)
Geolocation               (1000163, 5)
Order Items               (112650, 7)
Order Payments            (103886, 5)
Order Reviews             (99224, 7)
Orders                    (99441, 8)
Products                  (32951, 9)
Sellers                   (3095, 4)
Category Translation      (71, 2)

In [6]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    print(df.columns.tolist())

======================================================================
CUSTOMERS
======================================================================
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

======================================================================
GEOLOCATION
======================================================================
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

======================================================================
ORDER ITEMS
======================================================================
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

======================================================================
ORDER PAYMENTS
======================================================================
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

======================================================================
ORDER REVIEWS
======================================================================
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

======================================================================
ORDERS
======================================================================
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

======================================================================
PRODUCTS
======================================================================
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

======================================================================
SELLERS
======================================================================
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

======================================================================
CATEGORY TRANSLATION
======================================================================
['product_category_name', 'product_category_name_english']

In [7]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    print(df.dtypes)

======================================================================
CUSTOMERS
======================================================================
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

======================================================================
GEOLOCATION
======================================================================
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

======================================================================
ORDER ITEMS
======================================================================
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

======================================================================
ORDER PAYMENTS
======================================================================
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

======================================================================
ORDER REVIEWS
======================================================================
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

======================================================================
ORDERS
======================================================================
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

======================================================================
PRODUCTS
======================================================================
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

======================================================================
SELLERS
======================================================================
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

======================================================================
CATEGORY TRANSLATION
======================================================================
product_category_name            str
product_category_name_english    str
dtype: object

In [8]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    print(df.isnull().sum())

======================================================================
CUSTOMERS
======================================================================
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

======================================================================
GEOLOCATION
======================================================================
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

======================================================================
ORDER ITEMS
======================================================================
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

======================================================================
ORDER PAYMENTS
======================================================================
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

======================================================================
ORDER REVIEWS
======================================================================
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

======================================================================
ORDERS
======================================================================
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

======================================================================
PRODUCTS
======================================================================
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

======================================================================
SELLERS
======================================================================
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

======================================================================
CATEGORY TRANSLATION
======================================================================
product_category_name            0
product_category_name_english    0
dtype: int64

In [9]:
for name, df in datasets.items():
    print(f"{name:<25} Duplicate Rows: {df.duplicated().sum()}")

Customers                 Duplicate Rows: 0
Geolocation               Duplicate Rows: 261831
Order Items               Duplicate Rows: 0
Order Payments            Duplicate Rows: 0
Order Reviews             Duplicate Rows: 0
Orders                    Duplicate Rows: 0
Products                  Duplicate Rows: 0
Sellers                   Duplicate Rows: 0
Category Translation      Duplicate Rows: 0

In [10]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    display(df.head())

======================================================================
CUSTOMERS
======================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

======================================================================
GEOLOCATION
======================================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

======================================================================
ORDER ITEMS
======================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

======================================================================
ORDER PAYMENTS
======================================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

======================================================================
ORDER REVIEWS
======================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa,2018-03-01 00:00:00,2018-03-02 10:26:53

======================================================================
ORDERS
======================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

======================================================================
PRODUCTS
======================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

======================================================================
SELLERS
======================================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

======================================================================
CATEGORY TRANSLATION
======================================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [11]:
customers_clean = customers.copy()
geolocation_clean = geolocation.copy()
order_items_clean = order_items.copy()
order_payments_clean = order_payments.copy()
order_reviews_clean = order_reviews.copy()
orders_clean = orders.copy()
products_clean = products.copy()
sellers_clean = sellers.copy()
category_translation_clean = category_translation.copy()

In [12]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    if col in orders_clean.columns:
        orders_clean[col] = pd.to_datetime(
            orders_clean[col],
            errors="coerce"
        )

In [13]:
clean_datasets = {
    "Customers": customers_clean,
    "Geolocation": geolocation_clean,
    "Order Items": order_items_clean,
    "Order Payments": order_payments_clean,
    "Order Reviews": order_reviews_clean,
    "Orders": orders_clean,
    "Products": products_clean,
    "Sellers": sellers_clean,
    "Category Translation": category_translation_clean
}

for name, df in clean_datasets.items():
    before = len(df)
    df.drop_duplicates(inplace=True)
    after = len(df)

    print(f"{name:<25} Removed: {before-after}")

Customers                 Removed: 0
Geolocation               Removed: 261831
Order Items               Removed: 0
Order Payments            Removed: 0
Order Reviews             Removed: 0
Orders                    Removed: 0
Products                  Removed: 0
Sellers                   Removed: 0
Category Translation      Removed: 0

In [14]:
for name, df in clean_datasets.items():

    missing = df.isnull().sum()
    missing = missing[missing > 0]

    print("\n" + "="*70)
    print(name)
    print("="*70)

    if len(missing) == 0:
        print("No Missing Values")
    else:
        print(missing.sort_values(ascending=False))

======================================================================
Customers
======================================================================
No Missing Values

======================================================================
Geolocation
======================================================================
No Missing Values

======================================================================
Order Items
======================================================================
No Missing Values

======================================================================
Order Payments
======================================================================
No Missing Values

======================================================================
Order Reviews
======================================================================
review_comment_title      87656
review_comment_message    58247
dtype: int64

======================================================================
Orders
======================================================================
order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
dtype: int64

======================================================================
Products
======================================================================
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

======================================================================
Sellers
======================================================================
No Missing Values

======================================================================
Category Translation
======================================================================
No Missing Values

In [15]:
orders_clean[date_columns].info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_purchase_timestamp       99441 non-null  datetime64[us]
 1   order_approved_at              99281 non-null  datetime64[us]
 2   order_delivered_carrier_date   97658 non-null  datetime64[us]
 3   order_delivered_customer_date  96476 non-null  datetime64[us]
 4   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5)
memory usage: 3.8 MB

In [16]:
summary = pd.DataFrame({
    "Rows": [df.shape[0] for df in clean_datasets.values()],
    "Columns": [df.shape[1] for df in clean_datasets.values()],
    "Missing Values": [df.isnull().sum().sum() for df in clean_datasets.values()],
    "Duplicate Rows": [df.duplicated().sum() for df in clean_datasets.values()]
}, index=clean_datasets.keys())

summary

                        Rows  Columns  Missing Values  Duplicate Rows
Customers              99441        5               0               0
Geolocation           738332        5               0               0
Order Items           112650        7               0               0
Order Payments        103886        5               0               0
Order Reviews          99224        7          145903               0
Orders                 99441        8            4908               0
Products               32951        9            2448               0
Sellers                 3095        4               0               0
Category Translation      71        2               0               0

In [17]:
customer_orders = customers_clean.merge(
    orders_clean,
    on="customer_id",
    how="left"
)

print(customer_orders.shape)
customer_orders.head()

(99441, 12)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15

In [18]:
customer_orders = customer_orders.merge(
    order_items_clean,
    on="order_id",
    how="left"
)

print(customer_orders.shape)

(113425, 18)

In [19]:
customer_orders = customer_orders.merge(
    order_payments_clean,
    on="order_id",
    how="left"
)

print(customer_orders.shape)

(118434, 22)

In [20]:
customer_orders = customer_orders.merge(
    order_reviews_clean,
    on="order_id",
    how="left"
)

print(customer_orders.shape)

(119143, 28)

In [21]:
customer_orders = customer_orders.merge(
    products_clean,
    on="product_id",
    how="left"
)

print(customer_orders.shape)

(119143, 36)

In [22]:
customer_orders = customer_orders.merge(
    sellers_clean,
    on="seller_id",
    how="left"
)

print(customer_orders.shape)

(119143, 39)

In [23]:
print("=" * 70)
print("MASTER DATASET")
print("=" * 70)

print("Shape :", customer_orders.shape)
print()

customer_orders.info()

======================================================================
MASTER DATASET
======================================================================
Shape : (119143, 39)

<class 'pandas.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   customer_id                    119143 non-null  str
 1   customer_unique_id             119143 non-null  str
 2   customer_zip_code_prefix       119143 non-null  int64
 3   customer_city                  119143 non-null  str
 4   customer_state                 119143 non-null  str
 5   order_id                       119143 non-null  str
 6   order_status                   119143 non-null  str
 7   order_purchase_timestamp       119143 non-null  datetime64[us]
 8   order_approved_at              118966 non-null  datetime64[us]
 9   order_delivered_carrier_date   117057 non-null  datetime64[us]
 10  order_delivered_customer_date  115722 non-null  datetime64[us]
 11  order_estimated_delivery_date  119143 non-null  datetime64[us]
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  str
 14  seller_id                      118310 non-null  str
 15  shipping_limit_date            118310 non-null  str
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  payment_sequential             119140 non-null  float64
 19  payment_type                   119140 non-null  str
 20  payment_installments           119140 non-null  float64
 21  payment_value                  119140 non-null  float64
 22  review_id                      118146 non-null  str
 23  review_score                   118146 non-null  float64
 24  review_comment_title           13989 non-null   str
 25  review_comment_message         50245 non-null   str
 26  review_creation_date           118146 non-null  str
 27  review_answer_timestamp        118146 non-null  str
 28  product_category_name          116601 non-null  str
 29  product_name_lenght            116601 non-null  float64
 30  product_description_lenght     116601 non-null  float64
 31  product_photos_qty             116601 non-null  float64
 32  product_weight_g               118290 non-null  float64
 33  product_length_cm              118290 non-null  float64
 34  product_height_cm              118290 non-null  float64
 35  product_width_cm               118290 non-null  float64
 36  seller_zip_code_prefix         118310 non-null  float64
 37  seller_city                    118310 non-null  str
 38  seller_state                   118310 non-null  str
dtypes: datetime64[us](5), float64(15), int64(1), str(18)
memory usage: 35.5 MB

In [24]:
customer_orders.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05,1.0,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88,1.0,credit_card,2.0,146.87,88b8b52d46df026a9d1ad2136a59b30b,4.0,NaN,NaN,2017-05-26 00:00:00,2017-05-30 22:34:40,moveis_escritorio,41.0,1141.0,1.0,8683.0,54.0,64.0,31.0,8577.0,itaquaquecetuba,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06,1.0,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.00,46.48,1.0,credit_card,8.0,335.48,02fc48a9efa3e3d0f1a8ea26507eeec3,5.0,NaN,NaN,2018-01-30 00:00:00,2018-02-10 22:43:29,utilidades_domesticas,43.0,1002.0,3.0,10150.0,89.0,15.0,40.0,88303.0,itajai,SC
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13,1.0,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79,1.0,credit_card,7.0,157.73,5ad6695d76ee186dc473c42706984d87,5.0,NaN,NaN,2018-06-15 00:00:00,2018-06-15 12:10:59,moveis_escritorio,55.0,955.0,1.0,8267.0,52.0,52.0,17.0,8577.0,itaquaquecetuba,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10,1.0,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36,1.0,credit_card,1.0,173.30,059a801bb31f6aab2266e672cab87bc5,5.0,NaN,NaN,2018-03-29 00:00:00,2018-04-02 18:36:47,moveis_escritorio,48.0,1066.0,1.0,12160.0,56.0,51.0,28.0,8577.0,itaquaquecetuba,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15,1.0,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.00,22.25,1.0,credit_card,8.0,252.25,8490879d58d6c5d7773f2739a03f089a,5.0,a melhor nota,O baratheon è esxelente Amo adoro o baratheon,2018-08-10 00:00:00,2018-08-17 01:59:52,casa_conforto,61.0,407.0,1.0,5200.0,45.0,15.0,35.0,14940.0,ibitinga,SP

In [25]:
from pathlib import Path

processed_path = Path("../data/processed")
processed_path.mkdir(parents=True, exist_ok=True)

customer_orders.to_csv(
    processed_path / "customer_orders_master.csv",
    index=False
)

print("Master dataset saved successfully.")

Master dataset saved successfully.

In [26]:
master_df = customer_orders.copy()

print(master_df.shape)
master_df.head()

(119143, 39)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05,1.0,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,2017-05-22 15:22:12,124.99,21.88,1.0,credit_card,2.0,146.87,88b8b52d46df026a9d1ad2136a59b30b,4.0,NaN,NaN,2017-05-26 00:00:00,2017-05-30 22:34:40,moveis_escritorio,41.0,1141.0,1.0,8683.0,54.0,64.0,31.0,8577.0,itaquaquecetuba,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06,1.0,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-01-18 20:58:32,289.00,46.48,1.0,credit_card,8.0,335.48,02fc48a9efa3e3d0f1a8ea26507eeec3,5.0,NaN,NaN,2018-01-30 00:00:00,2018-02-10 22:43:29,utilidades_domesticas,43.0,1002.0,3.0,10150.0,89.0,15.0,40.0,88303.0,itajai,SC
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13,1.0,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,2018-06-05 16:19:10,139.94,17.79,1.0,credit_card,7.0,157.73,5ad6695d76ee186dc473c42706984d87,5.0,NaN,NaN,2018-06-15 00:00:00,2018-06-15 12:10:59,moveis_escritorio,55.0,955.0,1.0,8267.0,52.0,52.0,17.0,8577.0,itaquaquecetuba,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10,1.0,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,2018-03-27 16:31:16,149.94,23.36,1.0,credit_card,1.0,173.30,059a801bb31f6aab2266e672cab87bc5,5.0,NaN,NaN,2018-03-29 00:00:00,2018-04-02 18:36:47,moveis_escritorio,48.0,1066.0,1.0,12160.0,56.0,51.0,28.0,8577.0,itaquaquecetuba,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15,1.0,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,2018-07-31 10:10:09,230.00,22.25,1.0,credit_card,8.0,252.25,8490879d58d6c5d7773f2739a03f089a,5.0,a melhor nota,O baratheon è esxelente Amo adoro o baratheon,2018-08-10 00:00:00,2018-08-17 01:59:52,casa_conforto,61.0,407.0,1.0,5200.0,45.0,15.0,35.0,14940.0,ibitinga,SP

In [27]:
master_df["total_price"] = (
    master_df["price"] +
    master_df["freight_value"]
)

In [30]:
reference_date = master_df["order_purchase_timestamp"].max()

print(reference_date)

2018-10-17 17:30:18

In [31]:
customer_features = (
    master_df
    .groupby("customer_unique_id")
    .agg(
        Recency=(
            "order_purchase_timestamp",
            lambda x: (reference_date - x.max()).days
        ),

        Frequency=(
            "order_id",
            "nunique"
        ),

        Monetary=(
            "total_price",
            "sum"
        ),

        Total_Orders=(
            "order_id",
            "nunique"
        ),

        Total_Spent=(
            "total_price",
            "sum"
        ),

        Average_Order_Value=(
            "total_price",
            "mean"
        ),

        Average_Review_Score=(
            "review_score",
            "mean"
        )
    )
    .reset_index()
)

In [32]:
delivery = (
    master_df
    .groupby("customer_unique_id")
    .apply(
        lambda x: (
            x["order_delivered_customer_date"] -
            x["order_purchase_timestamp"]
        ).dt.days.mean()
    )
    .reset_index(name="Average_Delivery_Days")
)

customer_features = customer_features.merge(
    delivery,
    on="customer_unique_id",
    how="left"
)

In [33]:
customer_features.head()

,customer_unique_id,Recency,Frequency,Monetary,Total_Orders,Total_Spent,Average_Order_Value,Average_Review_Score,Average_Delivery_Days
0,0000366f3b9a7992bf8c76cfdf3221e2,160,1,141.90,1,141.90,141.90,5.0,6.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,163,1,27.19,1,27.19,27.19,4.0,3.0
2,0000f46a3911fa3c0805444483337064,585,1,86.22,1,86.22,86.22,3.0,25.0
3,0000f6ccb0745a6a4b88665a16c9f078,369,1,43.62,1,43.62,43.62,4.0,20.0
4,0004aac84e0df4da2b147fca70cf8255,336,1,196.89,1,196.89,196.89,5.0,13.0

In [34]:
customer_features.isnull().sum()

customer_unique_id          0
Recency                     0
Frequency                   0
Monetary                    0
Total_Orders                0
Total_Spent                 0
Average_Order_Value       676
Average_Review_Score      716
Average_Delivery_Days    2740
dtype: int64

In [35]:
customer_features.to_csv(
    "../data/processed/customer_features.csv",
    index=False
)

print("customer_features.csv saved successfully.")

customer_features.csv saved successfully.

In [36]:
ml_dataset = customer_features.copy()

ml_dataset.head()

,customer_unique_id,Recency,Frequency,Monetary,Total_Orders,Total_Spent,Average_Order_Value,Average_Review_Score,Average_Delivery_Days
0,0000366f3b9a7992bf8c76cfdf3221e2,160,1,141.90,1,141.90,141.90,5.0,6.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,163,1,27.19,1,27.19,27.19,4.0,3.0
2,0000f46a3911fa3c0805444483337064,585,1,86.22,1,86.22,86.22,3.0,25.0
3,0000f6ccb0745a6a4b88665a16c9f078,369,1,43.62,1,43.62,43.62,4.0,20.0
4,0004aac84e0df4da2b147fca70cf8255,336,1,196.89,1,196.89,196.89,5.0,13.0

In [37]:
ml_dataset["Churn"] = (
    ml_dataset["Recency"] > 180
).astype(int)

In [38]:
def customer_segment(row):

    if row["Monetary"] >= 1000:
        return "High Value"

    elif row["Frequency"] >= 5:
        return "Loyal"

    elif row["Recency"] <= 60:
        return "Active"

    else:
        return "Regular"


ml_dataset["Customer_Segment"] = ml_dataset.apply(
    customer_segment,
    axis=1
)

In [39]:
ml_dataset["Predicted_CLV"] = (
    ml_dataset["Total_Spent"] *
    ml_dataset["Frequency"]
)

In [40]:
ml_dataset["Purchase_Propensity"] = (
    ml_dataset["Recency"] <= 90
).astype(int)

In [41]:
print(ml_dataset.shape)

ml_dataset.head()

(96096, 13)

,customer_unique_id,Recency,Frequency,Monetary,Total_Orders,Total_Spent,Average_Order_Value,Average_Review_Score,Average_Delivery_Days,Churn,Customer_Segment,Predicted_CLV,Purchase_Propensity
0,0000366f3b9a7992bf8c76cfdf3221e2,160,1,141.90,1,141.90,141.90,5.0,6.0,0,Regular,141.90,0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,163,1,27.19,1,27.19,27.19,4.0,3.0,0,Regular,27.19,0
2,0000f46a3911fa3c0805444483337064,585,1,86.22,1,86.22,86.22,3.0,25.0,1,Regular,86.22,0
3,0000f6ccb0745a6a4b88665a16c9f078,369,1,43.62,1,43.62,43.62,4.0,20.0,1,Regular,43.62,0
4,0004aac84e0df4da2b147fca70cf8255,336,1,196.89,1,196.89,196.89,5.0,13.0,1,Regular,196.89,0

In [42]:
ml_dataset.to_csv(
    "../data/processed/ml_dataset.csv",
    index=False
)

print("ml_dataset.csv created successfully.")

ml_dataset.csv created successfully.

In [43]:
print("Churn Distribution")
print(ml_dataset["Churn"].value_counts())

print()

print("Customer Segments")
print(ml_dataset["Customer_Segment"].value_counts())

print()

print("Purchase Propensity")
print(ml_dataset["Purchase_Propensity"].value_counts())

Churn Distribution
Churn
1    68115
0    27981
Name: count, dtype: int64

Customer Segments
Customer_Segment
Regular       93047
Active         1658
High Value     1378
Loyal            13
Name: count, dtype: int64

Purchase Propensity
Purchase_Propensity
0    86432
1     9664
Name: count, dtype: int64